### ISSUE TITLE
Bug: can't access to the app (lucide_icon problem)

### ISSUE THREAD

**Issue by hecht-a** [maybe-finance/maybe#1655]
Hello, after upgrading from v0.2.0 to v0.3.0 I have a problem and I can't access the application except for a few URLs.

**Describe the bug**
I think the problem is with the categories. The category icons weren't in v0.2.0 so after updating to v0.3.0, all the categories created in the previous version don't match the new template. When trying to display an icon from an old category, the application crashes as there is no icon.

For example, I can access to : 
- /feedback
- /settings/preferences
- /settings/profile

But can't access to : 
- /
- /categories

This is just a guess, I'm not sure. Here's the error I got : 
```txt
I, [2025-01-22T20:16:36.049629 #1]  INFO -- : [01ab9b2d-5827-497a-89cd-cee2040d3f8a] Started GET "/" for 10.0.0.2 at 2025-01-22 20:16:36 +0000
I, [2025-01-22T20:16:36.051747 #1]  INFO -- : [01ab9b2d-5827-497a-89cd-cee2040d3f8a] Processing by PagesController#dashboard as HTML
I, [2025-01-22T20:16:37.310512 #1]  INFO -- : [01ab9b2d-5827-497a-89cd-cee2040d3f8a]   Rendered layout layouts/with_sidebar.html.erb (Duration: 1001.0ms | GC: 18.4ms)
I, [2025-01-22T20:16:37.310823 #1]  INFO -- : [01ab9b2d-5827-497a-89cd-cee2040d3f8a] Completed 500 Internal Server Error in 1259ms (ActiveRecord: 67.2ms (44 queries, 0 cached) | GC: 22.3ms)
E, [2025-01-22T20:16:37.314521 #1] ERROR -- : [01ab9b2d-5827-497a-89cd-cee2040d3f8a]   
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] ActionView::Template::Error (undefined method `lucide_icon' for an instance of Category):
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] 
Causes:
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] NoMethodError (undefined method `lucide_icon' for an instance of Category)
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]      7:           background-color: color-mix(in srgb, <%= category.color %> 5%, white);
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]      8:           border-color: color-mix(in srgb, <%= category.color %> 30%, white);
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]      9:           color: <%= category.color %>;">
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]     10:     <% if category.lucide_icon.present? %>
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]     11:       <%= lucide_icon category.lucide_icon, class: "w-4 h-4 shrink-0" %>
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]     12:     <% end %>
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]     13:     <%= category.name %>
[01ab9b2d-5827-497a-89cd-cee2040d3f8a]   
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/categories/_badge.html.erb:10
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/categories/_menu.html.erb:5
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/account/transactions/_transaction_category.html.erb:5
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/account/transactions/_transaction.html.erb:58
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/account/entries/_entry.html.erb:4
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/account/entries/_entry.html.erb:3
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/pages/dashboard.html.erb:194
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/helpers/account/entries_helper.rb:14:in `block (2 levels) in entries_by_date'
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/helpers/account/entries_helper.rb:13:in `block in entries_by_date'
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/helpers/account/entries_helper.rb:12:in `each'
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/helpers/account/entries_helper.rb:12:in `map'
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/helpers/account/entries_helper.rb:12:in `entries_by_date'
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/views/pages/dashboard.html.erb:193
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/controllers/concerns/localize.rb:17:in `switch_timezone'
[01ab9b2d-5827-497a-89cd-cee2040d3f8a] app/controllers/concerns/localize.rb:12:in `switch_locale'
```

**What version of Maybe are you using?**
Self-hosted, v0.3.0

**Comment by hecht-a** [comment]
I tried the v0.3.0 in my computer. I see that I have 2 more tables in the database compared to the database on my server.

Also, in the categories table there are differences : 

local : 
![Image](https://github.com/user-attachments/assets/356e0bc1-6551-420c-8733-1345a19bc206)

server : 
![Image](https://github.com/user-attachments/assets/f21f658d-973b-474b-90ca-90ff06a89698)

**Comment by zachgoll** [comment]
@hecht-a this is because the latest DB migrations did not properly run on your instance.  One of the most recent migrations added the `lucide_icon` property to the `Category` model, but because your migration didn't run, the DB doesn't have it.

Unfortunately there's not much I can help with here other than pointing towards those DB migrations—you'll want to figure out why those didn't run (they should automatically each time you pull down the new image and restart).

**Comment by hecht-a** [comment]
Maybe it's because I run the app with docker swarm. I don't really know how are managed docker images with swarm 🤔 
I'll check into it

**Comment by hecht-a** [comment]
I found the problem. With swarm the `depends_on` option is not supported in compose file so I replaced that with an `entrypoint` that checks if the db is ready and starts the server. This entrypoint overrides the one defined in the Dockerfile (docker-entrypoint) so the migrations were not applied.

Thanks for the help, you can close the issue 😄
